version: '2'
services:
  web:
    restart: 'always'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/files
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://ndo:ndo@db:5432/ndodb
      - FILES_DIR=/files
    depends_on:
      - "db"
  db:
    restart: 'always'
    image: postgres:9.6
    volumes:
      - ./ndodb-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ndo
      - POSTGRES_PASSWORD=ndo
      - POSTGRES_DB=ndodb
